version: '3.8'

services:
  twilio-proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    container_name: zitadel-twilio-proxy
    ports:
      - "8080:8080"
    environment:
      # Proxy Configuration
      PORT: 8080
      AUTH_REQUIRED: "true"
      
      # Expected credentials from Zitadel (what you configure in Zitadel)
      EXPECTED_ACCOUNT_SID: "ACyour-dummy-account-sid"
      EXPECTED_AUTH_TOKEN: "your-dummy-auth-token"
      
      # Actual SMS Provider Selection (messagebird, vonage, custom)
      SMS_PROVIDER: messagebird
      
      # MessageBird Configuration
      MESSAGEBIRD_ACCESS_KEY: ${MESSAGEBIRD_ACCESS_KEY}
      MESSAGEBIRD_FROM: ${MESSAGEBIRD_FROM:-Zitadel}
      
      # Vonage Configuration
      VONAGE_API_KEY: ${VONAGE_API_KEY}
      VONAGE_API_SECRET: ${VONAGE_API_SECRET}
      VONAGE_FROM: ${VONAGE_FROM:-Zitadel}
      
      # Custom Provider Configuration
      CUSTOM_SMS_ENDPOINT: ${CUSTOM_SMS_ENDPOINT}
      CUSTOM_SMS_API_KEY: ${CUSTOM_SMS_API_KEY}
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    networks:
      - proxy-network

  # Example Zitadel configuration (adjust to your setup)
  zitadel:
    image: ghcr.io/zitadel/zitadel:v2.42.0
    container_name: zitadel
    environment:
      # Point Zitadel to use the proxy instead of real Twilio
      ZITADEL_NOTIFYPROVIDER_TWILIOBASEURL: "http://twilio-proxy:8080"
      ZITADEL_NOTIFYPROVIDER_TWILIOAPIKEY: "ACyour-dummy-account-sid"
      ZITADEL_NOTIFYPROVIDER_TWILIOAUTHTOKEN: "your-dummy-auth-token"
      ZITADEL_NOTIFYPROVIDER_TWILIOSENDERID: "+1234567890"
      
      # Other Zitadel configuration...
      # Add your database, domain, and other settings here
    
    depends_on:
      - twilio-proxy
    
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge