version: '3.8'

services:
  sms-webhook:
    build: .
    container_name: zitadel-sms-webhook
    ports:
      - "5000:5000"
    environment:
      # Webhook Configuration
      - WEBHOOK_SECRET=your-secure-webhook-secret
      - PORT=5000
      - DEBUG=false
      
      # SMS Provider Selection (twilio, messagebird, vonage, custom)
      - SMS_PROVIDER=twilio
      
      # Twilio Configuration
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_FROM_NUMBER=${TWILIO_FROM_NUMBER}
      
      # MessageBird Configuration
      - MESSAGEBIRD_ACCESS_KEY=${MESSAGEBIRD_ACCESS_KEY}
      - MESSAGEBIRD_FROM=Zitadel
      
      # Vonage Configuration
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_FROM=Zitadel
      
      # Custom Provider Configuration
      - CUSTOM_SMS_ENDPOINT=${CUSTOM_SMS_ENDPOINT}
      - CUSTOM_SMS_API_KEY=${CUSTOM_SMS_API_KEY}
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    networks:
      - sms-network

  # Optional: Nginx reverse proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: sms-webhook-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - sms-webhook
    networks:
      - sms-network
    profiles:
      - with-ssl

networks:
  sms-network:
    driver: bridge