name: openedx-lms-development-settings
content: |
  # Force disable all login views in development
  from django.views.generic import RedirectView
  from django.urls import reverse_lazy
  
  # Override the login view class if it exists
  try:
      from openedx.core.djangoapps.user_authn.views.login import LoginSessionView
      LoginSessionView.dispatch = lambda self, request, *args, **kwargs: redirect('{{ SSO_REDIRECT_URL }}')
  except ImportError:
      pass
  
  # Force redirect any view that might render login forms
  FEATURES['ENABLE_AUTHN_MICROFRONTEND'] = False
  FEATURES['DISABLE_ACCOUNT_REGISTRATION'] = True