name: openedx-lms-common-settings
content: |
  # Additional SSO Redirect Settings
  
  # Completely disable registration
  FEATURES['ALLOW_PUBLIC_ACCOUNT_CREATION'] = False
  
  # Hide login/register links from navigation
  FEATURES['ENABLE_ACCOUNT_ACTIVATION'] = False
  FEATURES['SKIP_EMAIL_VERIFICATION'] = True
  
  # Configure URL overrides
  REGISTRATION_REDIRECT_URL = '{{ SSO_OIDC_ENDPOINT }}'
  
  # Disable all password-related features
  FEATURES['ENABLE_CHANGE_USER_PASSWORD_ADMIN'] = False
  FEATURES['ENABLE_ACCOUNT_PASSWORD_RESET'] = False
  
  # Third-party auth provider settings
  THIRD_PARTY_AUTH_BACKENDS = ['social_core.backends.azuread.AzureADOAuth2']
  
  # Override login/logout URLs
  LOGIN_URL = '{{ SSO_OIDC_ENDPOINT }}'
  LOGOUT_URL = '/logout'
  
  # Session settings
  SESSION_COOKIE_NAME = 'sessionid'
  SESSION_COOKIE_DOMAIN = FEATURES.get('SESSION_COOKIE_DOMAIN', '')
  
  # OIDC-specific settings
  SOCIAL_AUTH_OIDC_OIDC_ENDPOINT = '{{ SSO_OIDC_ENDPOINT }}'
  SOCIAL_AUTH_OIDC_KEY = ''  # Will be configured by admin
  SOCIAL_AUTH_OIDC_SECRET = ''  # Will be configured by admin